// <auto-generated />
namespace IdmanistData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcustomer_id_foreign_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcustomer_id_foreign_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201709131145033_addcustomer_id_foreign_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
