// <auto-generated />
namespace IdmanistData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMigrationForeignKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMigrationForeignKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201709111206399_Add-Migration 'Foreign Key'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
